export const INQUIRY_LIST_REQUEST = 'INQUIRY_LIST_REQUEST';
export const INQUIRY_LIST_SUCCESS = 'INQUIRY_LIST_SUCCESS';
export const INQUIRY_LIST_FAIL = 'INQUIRY_LIST_FAIL';

export const INQUIRY_DETAILS_REQUEST = 'INQUIRY_DETAILS_REQUEST';
export const INQUIRY_DETAILS_SUCCESS = 'INQUIRY_DETAILS_SUCCESS';
export const INQUIRY_DETAILS_FAIL = 'INQUIRY_DETAILS_FAIL';

export const INQUIRY_CREATE_REQUEST = 'INQUIRY_CREATE_REQUEST';
export const INQUIRY_CREATE_SUCCESS = 'INQUIRY_CREATE_SUCCESS';
export const INQUIRY_CREATE_FAIL = 'INQUIRY_CREATE_FAIL';

export const INQUIRY_UPDATE_REQUEST = 'INQUIRY_UPDATE_REQUEST';
export const INQUIRY_UPDATE_SUCCESS = 'INQUIRY_UPDATE_SUCCESS';
export const INQUIRY_UPDATE_FAIL = 'INQUIRY_UPDATE_FAIL';

export const INQUIRY_DELETE_REQUEST = 'INQUIRY_DELETE_REQUEST';
export const INQUIRY_DELETE_SUCCESS = 'INQUIRY_DELETE_SUCCESS';
export const INQUIRY_DELETE_FAIL = 'INQUIRY_DELETE_FAIL';
